// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4zV_DTDYW7e1qdPbgCk7NN4fqxRvODKk',
    appId: '1:671636856087:web:3ad70972fdc11bf2a36b52',
    messagingSenderId: '671636856087',
    projectId: 'soldiersfriends',
    authDomain: 'soldiersfriends.firebaseapp.com',
    storageBucket: 'soldiersfriends.firebasestorage.app',
    measurementId: 'G-N8ZEKGX24K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0OoNCwKloJ1iHTYgc1k6t-UZ63HB9DY8',
    appId: '1:671636856087:android:b93d5e0365732de7a36b52',
    messagingSenderId: '671636856087',
    projectId: 'soldiersfriends',
    storageBucket: 'soldiersfriends.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvTb8Y3JI3EFlyBIjWXrUaObxUG-mbG4A',
    appId: '1:671636856087:ios:2129480a8ca2ddaca36b52',
    messagingSenderId: '671636856087',
    projectId: 'soldiersfriends',
    storageBucket: 'soldiersfriends.firebasestorage.app',
    iosClientId: '671636856087-evsquiu7au7gscob7hrt9ci1hn0n8d6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.soldiersFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvTb8Y3JI3EFlyBIjWXrUaObxUG-mbG4A',
    appId: '1:671636856087:ios:2129480a8ca2ddaca36b52',
    messagingSenderId: '671636856087',
    projectId: 'soldiersfriends',
    storageBucket: 'soldiersfriends.firebasestorage.app',
    iosClientId: '671636856087-evsquiu7au7gscob7hrt9ci1hn0n8d6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.soldiersFriends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4zV_DTDYW7e1qdPbgCk7NN4fqxRvODKk',
    appId: '1:671636856087:web:f104c9b6b7f2d3d5a36b52',
    messagingSenderId: '671636856087',
    projectId: 'soldiersfriends',
    authDomain: 'soldiersfriends.firebaseapp.com',
    storageBucket: 'soldiersfriends.firebasestorage.app',
    measurementId: 'G-F0ZME66VM4',
  );

}