// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPfjcRG4QpG0RzQDyBfq_rl4gFKouWDMU',
    appId: '1:177377617100:web:67c7782ded89a37d42ce69',
    messagingSenderId: '177377617100',
    projectId: 'soldiers-friends-18909',
    authDomain: 'soldiers-friends-18909.firebaseapp.com',
    storageBucket: 'soldiers-friends-18909.firebasestorage.app',
    measurementId: 'G-N81238V8LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDttuEX877jGA5Guvv-w6vfc7zBaBA-8_g',
    appId: '1:177377617100:android:313a99d78d57588a42ce69',
    messagingSenderId: '177377617100',
    projectId: 'soldiers-friends-18909',
    storageBucket: 'soldiers-friends-18909.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnqD0B-p55Gvo0N8bsBnG9n3o3rq04RSI',
    appId: '1:177377617100:ios:b6eb2c00eb66922742ce69',
    messagingSenderId: '177377617100',
    projectId: 'soldiers-friends-18909',
    storageBucket: 'soldiers-friends-18909.firebasestorage.app',
    androidClientId: '177377617100-8d6lsvqo63gijp7mmcv4gn8js14k9bko.apps.googleusercontent.com',
    iosClientId: '177377617100-g6kimde0jn3llvme4tl4fb1e66oueo6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.soldiersFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnqD0B-p55Gvo0N8bsBnG9n3o3rq04RSI',
    appId: '1:177377617100:ios:b6eb2c00eb66922742ce69',
    messagingSenderId: '177377617100',
    projectId: 'soldiers-friends-18909',
    storageBucket: 'soldiers-friends-18909.firebasestorage.app',
    androidClientId: '177377617100-8d6lsvqo63gijp7mmcv4gn8js14k9bko.apps.googleusercontent.com',
    iosClientId: '177377617100-g6kimde0jn3llvme4tl4fb1e66oueo6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.soldiersFriends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPfjcRG4QpG0RzQDyBfq_rl4gFKouWDMU',
    appId: '1:177377617100:web:b920bb2bebf0479342ce69',
    messagingSenderId: '177377617100',
    projectId: 'soldiers-friends-18909',
    authDomain: 'soldiers-friends-18909.firebaseapp.com',
    storageBucket: 'soldiers-friends-18909.firebasestorage.app',
    measurementId: 'G-ZCWTEGKXQL',
  );
}
